export const mockAfricanBeneficiaries = [
  {
    "payeeIdentity": "ZW0000000000000001",
    "paymentModality": "00",
    "bankingInstitutionCode": "SBZAZAJJ",
    "financialAddress": "ZA930000001000000001",
    "firstName": "Tendai",
    "middleName": "James",
    "lastName": "Mukamuri",
    "dateOfBirth": "1955-03-15",
    "gender": "M",
    "nationality": "ZWE",
    "status": "ACTIVE",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000001",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2028-05-20",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000001-A-12",
    "taxIdentificationNumber": "ZW-TAX-0000000001",
    "phoneNumberPrimary": "+27-21-111-1111",
    "phoneNumberSecondary": "+263-4-111-111",
    "emailAddressPrimary": "tendai.mukamuri1@email.com",
    "emailAddressSecondary": "t.mukamuri1@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "12 Vilakazi Street",
    "currentAddressLine2": "Apartment 1A",
    "currentCity": "Johannesburg",
    "currentStateProvince": "Gauteng",
    "currentPostalCode": "2001",
    "currentCountry": "ZAF",
    "homeAddressLine1": "25 Samora Machel Avenue",
    "homeAddressLine2": "",
    "homeCity": "Harare",
    "homeStateProvince": "Harare Province",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Mary Mukamuri",
    "emergencyContactRelationship": "Spouse",
    "emergencyContactPhone": "+27-21-111-1112",
    "emergencyContactEmail": "mary.mukamuri@email.com",
    "emergencyContactAddress": "12 Vilakazi Street, Apartment 1A, Johannesburg, 2001, South Africa",
    "monthlyPensionAmount": 3200.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "Standard Bank of South Africa",
    "bankBranch": "Johannesburg Central",
    "accountHolderName": "Tendai James Mukamuri",
    "pensionStartDate": "2020-04-01",
    "lastEmploymentDate": "2020-03-31",
    "pensionType": "STATE_PENSION",
    "serviceYears": 35,
    "lastReviewDate": "2024-01-01",
    "nextReviewDate": "2025-01-01",
    "emigrationDate": "2018-06-15",
    "residencePermitNumber": "SA-RP-2018-000001",
    "residencePermitExpiry": "2026-06-14",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-01-15",
    "createdBy": "admin_user_001",
    "createdDate": "2024-01-15T09:30:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  },
 {
    "payeeIdentity": "ZW0000000000000002",
    "paymentModality": "00",
    "bankingInstitutionCode": "FNBSAJJ",
    "financialAddress": "ZA930000001000000002",
    "firstName": "Chipo",
    "middleName": "Rose",
    "lastName": "Chikafu",
    "dateOfBirth": "1958-07-19",
    "gender": "F",
    "nationality": "ZWE",
    "status": "ACTIVE",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000002",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2029-08-19",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000002-B-45",
    "taxIdentificationNumber": "ZW-TAX-0000000002",
    "phoneNumberPrimary": "+27-31-222-2222",
    "phoneNumberSecondary": "+263-4-222-222",
    "emailAddressPrimary": "chipo.chikafu@email.com",
    "emailAddressSecondary": "c.chikafu@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "102 Long Street",
    "currentAddressLine2": "Flat 3C",
    "currentCity": "Cape Town",
    "currentStateProvince": "Western Cape",
    "currentPostalCode": "8001",
    "currentCountry": "ZAF",
    "homeAddressLine1": "47 Mbuya Nehanda St",
    "homeAddressLine2": "",
    "homeCity": "Bulawayo",
    "homeStateProvince": "Bulawayo Province",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Blessing Chikafu",
    "emergencyContactRelationship": "Brother",
    "emergencyContactPhone": "+27-31-222-2223",
    "emergencyContactEmail": "blessing.chikafu@email.com",
    "emergencyContactAddress": "102 Long Street, Flat 3C, Cape Town, 8001, South Africa",
    "monthlyPensionAmount": 2890.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "First National Bank",
    "bankBranch": "Cape Town Central",
    "accountHolderName": "Chipo Rose Chikafu",
    "pensionStartDate": "2021-02-01",
    "lastEmploymentDate": "2020-12-31",
    "pensionType": "STATE_PENSION",
    "serviceYears": 37,
    "lastReviewDate": "2024-03-01",
    "nextReviewDate": "2025-03-01",
    "emigrationDate": "2017-09-10",
    "residencePermitNumber": "SA-RP-2017-000002",
    "residencePermitExpiry": "2025-09-09",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-03-15",
    "createdBy": "admin_user_002",
    "createdDate": "2024-03-15T10:15:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  },
  {
    "payeeIdentity": "ZW0000000000000003",
    "paymentModality": "00",
    "bankingInstitutionCode": "ABSAZAJJ",
    "financialAddress": "ZA930000001000000003",
    "firstName": "Farai",
    "middleName": "Peter",
    "lastName": "Ncube",
    "dateOfBirth": "1960-10-30",
    "gender": "M",
    "nationality": "ZWE",
    "status": "ACTIVE",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000003",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2028-10-30",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000003-C-87",
    "taxIdentificationNumber": "ZW-TAX-0000000003",
    "phoneNumberPrimary": "+27-11-333-3333",
    "phoneNumberSecondary": "+263-4-333-333",
    "emailAddressPrimary": "farai.ncube@email.com",
    "emailAddressSecondary": "f.ncube@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "88 Jan Smuts Avenue",
    "currentAddressLine2": "Unit 12",
    "currentCity": "Randburg",
    "currentStateProvince": "Gauteng",
    "currentPostalCode": "2194",
    "currentCountry": "ZAF",
    "homeAddressLine1": "11 Herbert Chitepo Avenue",
    "homeAddressLine2": "",
    "homeCity": "Mutare",
    "homeStateProvince": "Manicaland Province",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Samantha Ncube",
    "emergencyContactRelationship": "Wife",
    "emergencyContactPhone": "+27-11-333-3334",
    "emergencyContactEmail": "samantha.ncube@email.com",
    "emergencyContactAddress": "88 Jan Smuts Avenue, Unit 12, Randburg, 2194, South Africa",
    "monthlyPensionAmount": 3100.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "ABSA Bank",
    "bankBranch": "Randburg Branch",
    "accountHolderName": "Farai Peter Ncube",
    "pensionStartDate": "2020-06-01",
    "lastEmploymentDate": "2020-05-31",
    "pensionType": "STATE_PENSION",
    "serviceYears": 36,
    "lastReviewDate": "2024-05-01",
    "nextReviewDate": "2025-05-01",
    "emigrationDate": "2016-05-15",
    "residencePermitNumber": "SA-RP-2016-000003",
    "residencePermitExpiry": "2024-05-14",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-05-15",
    "createdBy": "admin_user_003",
    "createdDate": "2024-05-15T11:00:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  },
  {
    "payeeIdentity": "ZW0000000000000004",
    "paymentModality": "00",
    "bankingInstitutionCode": "SBZAZAJJ",
    "financialAddress": "ZA930000001000000004",
    "firstName": "Nomsa",
    "middleName": "Grace",
    "lastName": "Maphosa",
    "dateOfBirth": "1952-11-25",
    "gender": "F",
    "nationality": "ZWE",
    "status": "PENDING",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000004",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2027-11-25",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000004-D-25",
    "taxIdentificationNumber": "ZW-TAX-0000000004",
    "phoneNumberPrimary": "+27-41-444-4444",
    "phoneNumberSecondary": "+263-4-444-444",
    "emailAddressPrimary": "nomsa.maphosa@email.com",
    "emailAddressSecondary": "n.maphosa@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "34 Govan Mbeki Avenue",
    "currentAddressLine2": "Suite 10",
    "currentCity": "Port Elizabeth",
    "currentStateProvince": "Eastern Cape",
    "currentPostalCode": "6001",
    "currentCountry": "ZAF",
    "homeAddressLine1": "19 J. Nyerere Street",
    "homeAddressLine2": "",
    "homeCity": "Masvingo",
    "homeStateProvince": "Masvingo Province",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Robert Maphosa",
    "emergencyContactRelationship": "Son",
    "emergencyContactPhone": "+27-41-444-4445",
    "emergencyContactEmail": "robert.maphosa@email.com",
    "emergencyContactAddress": "34 Govan Mbeki Avenue, Suite 10, Port Elizabeth, 6001, South Africa",
    "monthlyPensionAmount": 2800.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "Standard Bank of South Africa",
    "bankBranch": "Port Elizabeth Main",
    "accountHolderName": "Nomsa Grace Maphosa",
    "pensionStartDate": "2019-11-01",
    "lastEmploymentDate": "2019-10-31",
    "pensionType": "STATE_PENSION",
    "serviceYears": 38,
    "lastReviewDate": "2024-09-01",
    "nextReviewDate": "2025-09-01",
    "emigrationDate": "2017-01-12",
    "residencePermitNumber": "SA-RP-2017-000004",
    "residencePermitExpiry": "2025-01-11",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-09-10",
    "createdBy": "admin_user_004",
    "createdDate": "2024-09-10T12:10:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  },
   {
    "payeeIdentity": "ZW0000000000000005",
    "paymentModality": "00",
    "bankingInstitutionCode": "CAPITECJJ",
    "financialAddress": "ZA930000001000000005",
    "firstName": "Patience",
    "middleName": "Faith",
    "lastName": "Zhou",
    "dateOfBirth": "1956-04-12",
    "gender": "F",
    "nationality": "ZWE",
    "status": "PENDING",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000005",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2026-04-12",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000005-E-10",
    "taxIdentificationNumber": "ZW-TAX-0000000005",
    "phoneNumberPrimary": "+27-21-555-5555",
    "phoneNumberSecondary": "+263-4-555-555",
    "emailAddressPrimary": "patience.zhou@email.com",
    "emailAddressSecondary": "p.zhou@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "78 Greenmarket Square",
    "currentAddressLine2": "Flat 5D",
    "currentCity": "Cape Town",
    "currentStateProvince": "Western Cape",
    "currentPostalCode": "8001",
    "currentCountry": "ZAF",
    "homeAddressLine1": "2 Tongogara Street",
    "homeAddressLine2": "",
    "homeCity": "Gweru",
    "homeStateProvince": "Midlands Province",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Eunice Zhou",
    "emergencyContactRelationship": "Sister",
    "emergencyContactPhone": "+27-21-555-5556",
    "emergencyContactEmail": "eunice.zhou@email.com",
    "emergencyContactAddress": "78 Greenmarket Square, Flat 5D, Cape Town, 8001, South Africa",
    "monthlyPensionAmount": 3000.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "Capitec Bank",
    "bankBranch": "Cape Town Branch",
    "accountHolderName": "Patience Faith Zhou",
    "pensionStartDate": "2020-03-01",
    "lastEmploymentDate": "2020-02-28",
    "pensionType": "STATE_PENSION",
    "serviceYears": 32,
    "lastReviewDate": "2024-06-01",
    "nextReviewDate": "2025-10-01",
    "emigrationDate": "2019-03-05",
    "residencePermitNumber": "SA-RP-2019-000005",
    "residencePermitExpiry": "2027-03-04",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-02-20",
    "createdBy": "admin_user_005",
    "createdDate": "2024-02-20T08:00:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  },
  {
    "payeeIdentity": "ZW0000000000000006",
    "paymentModality": "00",
    "bankingInstitutionCode": "SBZAZAJJ",
    "financialAddress": "ZA930000001000000006",
    "firstName": "Simba",
    "middleName": "John",
    "lastName": "Mutasa",
    "dateOfBirth": "1953-01-17",
    "gender": "M",
    "nationality": "ZWE",
    "status": "REJECTED",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000006",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2027-01-17",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000006-F-22",
    "taxIdentificationNumber": "ZW-TAX-0000000006",
    "phoneNumberPrimary": "+27-12-666-6666",
    "phoneNumberSecondary": "+263-4-666-666",
    "emailAddressPrimary": "simba.mutasa@email.com",
    "emailAddressSecondary": "s.mutasa@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "501 Stanza Bopape Street",
    "currentAddressLine2": "",
    "currentCity": "Pretoria",
    "currentStateProvince": "Gauteng",
    "currentPostalCode": "0002",
    "currentCountry": "ZAF",
    "homeAddressLine1": "8 Sixth Avenue",
    "homeAddressLine2": "",
    "homeCity": "Mutoko",
    "homeStateProvince": "Mashonaland East",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Tariro Mutasa",
    "emergencyContactRelationship": "Daughter",
    "emergencyContactPhone": "+27-12-666-6667",
    "emergencyContactEmail": "tariro.mutasa@email.com",
    "emergencyContactAddress": "501 Stanza Bopape Street, Pretoria, 0002, South Africa",
    "monthlyPensionAmount": 3150.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "Standard Bank of South Africa",
    "bankBranch": "Pretoria Main",
    "accountHolderName": "Simba John Mutasa",
    "pensionStartDate": "2018-01-01",
    "lastEmploymentDate": "2017-12-31",
    "pensionType": "STATE_PENSION",
    "serviceYears": 34,
    "lastReviewDate": "2024-07-01",
    "nextReviewDate": "2025-07-01",
    "emigrationDate": "2017-06-18",
    "residencePermitNumber": "SA-RP-2017-000006",
    "residencePermitExpiry": "2025-06-17",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-07-20",
    "createdBy": "admin_user_006",
    "createdDate": "2024-07-20T15:00:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  },
  {
    "payeeIdentity": "ZW0000000000000007",
    "paymentModality": "00",
    "bankingInstitutionCode": "FNBSAJJ",
    "financialAddress": "ZA930000001000000007",
    "firstName": "Tatenda",
    "middleName": "Peter",
    "lastName": "Moyo",
    "dateOfBirth": "1954-08-05",
    "gender": "M",
    "nationality": "ZWE",
    "status": "REJECTED",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000007",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2027-08-05",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000007-G-55",
    "taxIdentificationNumber": "ZW-TAX-0000000007",
    "phoneNumberPrimary": "+27-21-777-7777",
    "phoneNumberSecondary": "+263-4-777-777",
    "emailAddressPrimary": "tatenda.moyo@email.com",
    "emailAddressSecondary": "t.moyo@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "10 Wale Street",
    "currentAddressLine2": "Apartment 7B",
    "currentCity": "Cape Town",
    "currentStateProvince": "Western Cape",
    "currentPostalCode": "8001",
    "currentCountry": "ZAF",
    "homeAddressLine1": "15 Mutare Road",
    "homeAddressLine2": "",
    "homeCity": "Chitungwiza",
    "homeStateProvince": "Mashonaland East",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Ruth Moyo",
    "emergencyContactRelationship": "Wife",
    "emergencyContactPhone": "+27-21-777-7778",
    "emergencyContactEmail": "ruth.moyo@email.com",
    "emergencyContactAddress": "10 Wale Street, Apartment 7B, Cape Town, 8001, South Africa",
    "monthlyPensionAmount": 2850.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "First National Bank",
    "bankBranch": "Cape Town Central",
    "accountHolderName": "Tatenda Peter Moyo",
    "pensionStartDate": "2019-04-01",
    "lastEmploymentDate": "2019-03-31",
    "pensionType": "STATE_PENSION",
    "serviceYears": 33,
    "lastReviewDate": "2024-04-01",
    "nextReviewDate": "2025-04-01",
    "emigrationDate": "2016-02-24",
    "residencePermitNumber": "SA-RP-2016-000007",
    "residencePermitExpiry": "2024-02-23",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-04-10",
    "createdBy": "admin_user_007",
    "createdDate": "2024-04-10T12:00:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  },
  {
    "payeeIdentity": "ZW0000000000000008",
    "paymentModality": "00",
    "bankingInstitutionCode": "CAPITECJJ",
    "financialAddress": "ZA930000001000000008",
    "firstName": "Linda",
    "middleName": "Joyce",
    "lastName": "Mawere",
    "dateOfBirth": "1959-02-20",
    "gender": "F",
    "nationality": "ZWE",
    "status": "REJECTED",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000008",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2029-02-20",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000008-H-21",
    "taxIdentificationNumber": "ZW-TAX-0000000008",
    "phoneNumberPrimary": "+27-21-888-8888",
    "phoneNumberSecondary": "+263-4-888-888",
    "emailAddressPrimary": "linda.mawere@email.com",
    "emailAddressSecondary": "l.mawere@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "42 Roeland Street",
    "currentAddressLine2": "Suite 9E",
    "currentCity": "Cape Town",
    "currentStateProvince": "Western Cape",
    "currentPostalCode": "8001",
    "currentCountry": "ZAF",
    "homeAddressLine1": "21 Jason Moyo Ave",
    "homeAddressLine2": "",
    "homeCity": "Bulawayo",
    "homeStateProvince": "Bulawayo Province",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Edwin Mawere",
    "emergencyContactRelationship": "Husband",
    "emergencyContactPhone": "+27-21-888-8889",
    "emergencyContactEmail": "edwin.mawere@email.com",
    "emergencyContactAddress": "42 Roeland Street, Suite 9E, Cape Town, 8001, South Africa",
    "monthlyPensionAmount": 2990.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "Capitec Bank",
    "bankBranch": "Cape Town Branch",
    "accountHolderName": "Linda Joyce Mawere",
    "pensionStartDate": "2022-03-01",
    "lastEmploymentDate": "2022-02-28",
    "pensionType": "STATE_PENSION",
    "serviceYears": 30,
    "lastReviewDate": "2024-03-01",
    "nextReviewDate": "2025-03-01",
    "emigrationDate": "2018-05-03",
    "residencePermitNumber": "SA-RP-2018-000008",
    "residencePermitExpiry": "2026-05-02",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-03-10",
    "createdBy": "admin_user_008",
    "createdDate": "2024-03-10T10:00:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  },
  {
    "payeeIdentity": "ZW0000000000000009",
    "paymentModality": "00",
    "bankingInstitutionCode": "ABSAZAJJ",
    "financialAddress": "ZA930000001000000009",
    "firstName": "Blessing",
    "middleName": "Timothy",
    "lastName": "Dube",
    "dateOfBirth": "1962-06-29",
    "gender": "M",
    "nationality": "ZWE",
    "status": "PENDING",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000009",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2028-06-29",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000009-J-39",
    "taxIdentificationNumber": "ZW-TAX-0000000009",
    "phoneNumberPrimary": "+27-31-999-9999",
    "phoneNumberSecondary": "+263-4-999-999",
    "emailAddressPrimary": "blessing.dube@email.com",
    "emailAddressSecondary": "b.dube@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "15 Margaret Mncadi Ave",
    "currentAddressLine2": "",
    "currentCity": "Durban",
    "currentStateProvince": "KwaZulu-Natal",
    "currentPostalCode": "4001",
    "currentCountry": "ZAF",
    "homeAddressLine1": "6 Leopold Takawira Ave",
    "homeAddressLine2": "",
    "homeCity": "Gweru",
    "homeStateProvince": "Midlands Province",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Rudo Dube",
    "emergencyContactRelationship": "Wife",
    "emergencyContactPhone": "+27-31-999-9990",
    "emergencyContactEmail": "rudo.dube@email.com",
    "emergencyContactAddress": "15 Margaret Mncadi Ave, Durban, 4001, South Africa",
    "monthlyPensionAmount": 3250.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "ABSA Bank",
    "bankBranch": "Durban Branch",
    "accountHolderName": "Blessing Timothy Dube",
    "pensionStartDate": "2020-10-01",
    "lastEmploymentDate": "2020-09-30",
    "pensionType": "STATE_PENSION",
    "serviceYears": 37,
    "lastReviewDate": "2025-07-01",
    "nextReviewDate": "2025-08-01",
    "emigrationDate": "2017-10-15",
    "residencePermitNumber": "SA-RP-2017-000009",
    "residencePermitExpiry": "2025-10-14",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-10-15",
    "createdBy": "admin_user_009",
    "createdDate": "2024-10-15T12:00:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  },
   {
    "payeeIdentity": "ZW0000000000000010",
    "paymentModality": "00",
    "bankingInstitutionCode": "SBZAZAJJ",
    "financialAddress": "ZA930000001000000010",
    "firstName": "Rudo",
    "middleName": "Mercy",
    "lastName": "Mugabe",
    "dateOfBirth": "1951-03-12",
    "gender": "F",
    "nationality": "ZWE",
    "status": "PENDING",
    "primaryDocumentType": "PASSPORT",
    "primaryDocumentNumber": "AN000010",
    "primaryDocumentCountry": "ZWE",
    "primaryDocumentExpiry": "2028-03-12",
    "secondaryDocumentType": "NATIONAL_ID",
    "secondaryDocumentNumber": "63-000010-K-19",
    "taxIdentificationNumber": "ZW-TAX-0000000010",
    "phoneNumberPrimary": "+27-12-101-0101",
    "phoneNumberSecondary": "+263-4-101-010",
    "emailAddressPrimary": "rudo.mugabe@email.com",
    "emailAddressSecondary": "r.mugabe@gmail.com",
    "preferredContactMethod": "EMAIL",
    "languagePreference": "en",
    "currentAddressLine1": "18 Francis Baard Street",
    "currentAddressLine2": "",
    "currentCity": "Pretoria",
    "currentStateProvince": "Gauteng",
    "currentPostalCode": "0002",
    "currentCountry": "ZAF",
    "homeAddressLine1": "17 Julius Nyerere Way",
    "homeAddressLine2": "",
    "homeCity": "Harare",
    "homeStateProvince": "Harare Province",
    "homePostalCode": "263",
    "homeCountry": "ZWE",
    "emergencyContactName": "Munyaradzi Mugabe",
    "emergencyContactRelationship": "Son",
    "emergencyContactPhone": "+27-12-101-0102",
    "emergencyContactEmail": "munya.mugabe@email.com",
    "emergencyContactAddress": "18 Francis Baard Street, Pretoria, 0002, South Africa",
    "monthlyPensionAmount": 3400.00,
    "currencyPreference": "ZWL",
    "paymentFrequency": "MONTHLY",
    "bankName": "Standard Bank of South Africa",
    "bankBranch": "Pretoria Main",
    "accountHolderName": "Rudo Mercy Mugabe",
    "pensionStartDate": "2020-02-01",
    "lastEmploymentDate": "2020-01-31",
    "pensionType": "STATE_PENSION",
    "serviceYears": 39,
    "lastReviewDate": "2025-07-20",
    "nextReviewDate": "2025-08-15",
    "emigrationDate": "2018-04-11",
    "residencePermitNumber": "SA-RP-2018-000010",
    "residencePermitExpiry": "2026-04-10",
    "taxTreatyApplicable": true,
    "withholdingTaxRate": 0.00,
    "complianceStatus": "COMPLIANT",
    "lastVerificationDate": "2024-02-10",
    "createdBy": "admin_user_010",
    "createdDate": "2024-02-10T09:00:00Z",
    "updatedBy": null,
    "updatedDate": null,
    "version": 1
  }
];